HydrogenHourlyMatching: 0
NetworkExpansion: 0
TimeDomainReductionFolder: "TDR_results"
WriteOutputs: "full"
SystemFolder: "system"
EnableJuMPStringNames: false
Trans_Loss_Segments: 1
ModelingtoGenerateAlternativeSlack: 0.1
PoliciesFolder: "policies"
MultiStage: 1
ComputeConflicts: 0
OverwriteResults: 0
ModelingToGenerateAlternatives: 0
MaxCapReq: 0
MinCapReq: 0
CO2Cap: 2
WriteShadowPrices: 1
MultiStageSettingsDict:
  Myopic: 0
  ConvergenceTolerance: 0.01
  WACC: 0.045
  StageLengths:
    - 10
    - 10
    - 10
  CurStage: 3
  NumStages: 3
OperationalReserves: 0
ParameterScale: 1
EnergyShareRequirement: 0
PrintModel: 0
TimeDomainReduction: 1
DC_OPF: 0
CapacityReserveMargin: 0
MethodofMorris: 0
StorageVirtualDischarge: 1
StorageLosses: 1
IncludeLossesInESR: 0
ResourcePoliciesFolder: "policy_assignments"
WriteOutputsSettingsDict:
  WriteReserveMarginWithWeights: true
  WriteStorage: true
  WriteStatus: true
  WriteRsv: true
  WriteNetRevenue: true
  WriteNWExpansion: true
  WriteSubsidyRevenue: true
  WriteTimeWeights: true
  WriteVREStor: true
  WriteCO2: true
  WriteESRPrices: true
  WriteReg: true
  WriteCurtailment: true
  WriteCapacityFactor: true
  WriteCommit: true
  WriteStart: true
  WriteReserveMargin: true
  WriteChargingCost: true
  WriteCapacityValue: true
  WriteEnergyRevenue: true
  WriteAngles: true
  WriteFuelConsumption: true
  WriteStorageDual: true
  WriteTransmissionLosses: true
  WriteTransmissionFlows: true
  WriteNSE: true
  WriteCO2Cap: true
  WriteOpWrapLDSStorInit: true
  WriteEmissions: true
  WriteESRRevenue: true
  WriteCapacity: true
  WriteVirtualDischarge: true
  WriteReserveMarginRevenue: true
  WriteOpWrapLDSdStor: true
  WriteMaintenance: true
  WritePower: true
  WriteReliability: true
  WriteCharge: true
  WriteShutdown: true
  WriteHydrogenPrices: true
  WriteReserveMarginSlack: true
  WriteCosts: true
  WriteMaxCapReq: true
  WriteHourlyMatchingPrices: true
  WritePowerBalance: true
  WriteMinCapReq: true
  WritePrice: true
VirtualChargeDischargeCost: 1
UCommit: 2
ResourcesFolder: "resources"
