IterativelyAddPeriods: 1
ExtremePeriods:
  Wind:
    System:
      Absolute:
        Min: 0
        Max: 0
      Integral:
        Min: 1
        Max: 0
    Zone:
      Absolute:
        Min: 0
        Max: 0
      Integral:
        Min: 0
        Max: 0
  Load:
    System:
      Absolute:
        Min: 0
        Max: 1
      Integral:
        Min: 0
        Max: 0
    Zone:
      Absolute:
        Min: 0
        Max: 0
      Integral:
        Min: 0
        Max: 0
  PV:
    System:
      Absolute:
        Min: 0
        Max: 0
      Integral:
        Min: 1
        Max: 0
    Zone:
      Absolute:
        Min: 0
        Max: 0
      Integral:
        Min: 0
        Max: 0
UseExtremePeriods: 1
MinPeriods: 5
MaxPeriods: 5
LoadWeight: 1
ClusterFuelPrices: 0
nReps: 100
Threshold: 0.05
TimestepsPerRepPeriod: 24
IterateMethod: "cluster"
ScalingMethod: "S"
ClusterMethod: "kmeans"
WeightTotal: 8760
