# Gurobi Solver Parameters
# Common solver settings
Feasib_Tol: 1.0e-06           # Constraint (primal) feasibility tolerances.
Optimal_Tol: 1e-3             # Dual feasibility tolerances.
TimeLimit: 200000             # Limits total time solver. (110000 before change 12102021)
Pre_Solve: 0                  # Controls presolve level. (1 before change 12102021)
Method: -1                    # Algorithm used to solve continuous models (including MIP root relaxation). (2 before change 12102021)

#Gurobi-specific solver settings
MIPGap: 0.01                  # Relative (p.u. of optimal) mixed integer optimality tolerance for MIP problems (ignored otherwise). (1e-4 before change 12102021)
BarConvTol: 1.0e-08           # Barrier convergence tolerance (determines when barrier terminates).
NumericFocus: 0               # Numerical precision emphasis.
Crossover: 0               # Barrier crossver strategy.
BarObjRng: 1e+75              # Sets the maximum absolute value of the objective function
PreDual: 0                    # Decides whether presolve should pass the primal or dual linear programming problem to the LP optimization algorithm.
AggFill: 10                   # Allowed fill during presolve aggregation.
