name: JuliaFormatter

on:
  pull_request:
  push:
    branches: [main]
    tags: ['*']

jobs:
  Format:
    runs-on: ubuntu-latest
    steps:
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1'
      - uses: actions/checkout@v3
      - name: Format check
        shell: julia --color=yes {0}
        run: |
          using Pkg
          Pkg.add(PackageSpec(name="JuliaFormatter", version="1"))          
          using JuliaFormatter
          format("src", verbose=true)
          format("test", verbose=true)
          format("docs", verbose=true)
          out = String(read(Cmd(`git diff`)))
          if isempty(out)
              exit(0)
          end
          @error "Some files have not been formatted !!!"
          write(stdout, out)
          exit(1)
      

